Repository zerotier/ZeroTierOne, pull requests merged in 2020-11, with the labels that each got.

#1233 Minor C++ optimizations
  controller/EmbeddedNetworkController.cpp
  controller/LFDB.cpp
  node/IncomingPacket.cpp
  node/Peer.cpp
  node/Topology.cpp
  one.cpp
  osdep/Binder.hpp
  osdep/OSUtils.cpp
  service/OneService.cpp
  service/SoftwareUpdater.cpp
Labels: code quality

#1194 Add support for Elbrus-family CPU
  make-linux.mk
Labels: Linux, Windows, build problem

#1191 Add support for armv7ve
  make-linux.mk
Labels: Android, build problem, embedded
